### ISSUE TITLE
Processing a large number of files causes an eventual error

### ISSUE THREAD

**Issue by phobetron** [shaiguitar/haml-i18n-extractor#26]
Opening lots of files simultaneously overwhelms Ruby. I'd suggest closing each file after it has been processed.

```
/path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/extraction/yaml_writer.rb:41:in `read': Too many open files @ rb_sysopen - /path_to_output/en.yml (Errno::EMFILE)
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/extraction/yaml_writer.rb:41:in `write_file'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/extraction/extractor.rb:47:in `run'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/flow/workflow.rb:71:in `process'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/flow/workflow.rb:50:in `block in run'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/flow/workflow.rb:49:in `each'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/flow/workflow.rb:49:in `run'
	from /path_to_gems/haml-i18n-extractor-0.5.9/lib/haml-i18n-extractor/flow/cli.rb:44:in `start'
	from /path_to_gems/haml-i18n-extractor-0.5.9/bin/haml-i18n-extractor:18:in `<top (required)>'
	from /path_to_bin/haml-i18n-extractor:23:in `load'
	from /path_to_bin/haml-i18n-extractor:23:in `<main>'
```

**Comment by shaiguitar** [comment]
Hey @phobetron  I haven't used this project in a while. I think there are forks that are more current with some tweaked features etc. https://github.com/COzero/haml-i18n-extractor is one of them. Good luck!

Shai
